// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEwsFpJB_DrilsINJBLYqr0GyrASghR3o',
    appId: '1:332265682357:web:99069fb4c7efce941355fc',
    messagingSenderId: '332265682357',
    projectId: 'listatarefasflutter',
    authDomain: 'listatarefasflutter.firebaseapp.com',
    databaseURL: 'https://listatarefasflutter-default-rtdb.firebaseio.com',
    storageBucket: 'listatarefasflutter.appspot.com',
    measurementId: 'G-VL6D08BP9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh033s33S-_AAcaGXBTzoO33FXyU1fr7k',
    appId: '1:332265682357:android:4cb0a867559902711355fc',
    messagingSenderId: '332265682357',
    projectId: 'listatarefasflutter',
    databaseURL: 'https://listatarefasflutter-default-rtdb.firebaseio.com',
    storageBucket: 'listatarefasflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8edCc2p7fPvtvmCE5TuLxR3IqckMfBYo',
    appId: '1:332265682357:ios:451f9591dd3143bc1355fc',
    messagingSenderId: '332265682357',
    projectId: 'listatarefasflutter',
    databaseURL: 'https://listatarefasflutter-default-rtdb.firebaseio.com',
    storageBucket: 'listatarefasflutter.appspot.com',
    iosClientId: '332265682357-qtf2p2v7i5frkr3lak070srmor07msdf.apps.googleusercontent.com',
    iosBundleId: 'br.com.adrimatec.projetoListaDeTarefas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8edCc2p7fPvtvmCE5TuLxR3IqckMfBYo',
    appId: '1:332265682357:ios:451f9591dd3143bc1355fc',
    messagingSenderId: '332265682357',
    projectId: 'listatarefasflutter',
    databaseURL: 'https://listatarefasflutter-default-rtdb.firebaseio.com',
    storageBucket: 'listatarefasflutter.appspot.com',
    iosClientId: '332265682357-qtf2p2v7i5frkr3lak070srmor07msdf.apps.googleusercontent.com',
    iosBundleId: 'br.com.adrimatec.projetoListaDeTarefas',
  );
}
